# -*- coding: utf-8 -*-
"""Lab Works(id:423).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJoH6iwG3vecuEbrFWJF8lkUsZjxN-Uh
"""

#Q1:While Loop
def count_down(n):
    if n <= 0:
        print("positive integer.")
        return
    while n > 0:
        print(n)
        n -= 1
count_down(3)

#Q2:For Loop
def sum_even_numbers(limit):
    total_sum = 0
    for number in range(1, limit + 1):
        if number % 2 == 0:
            total_sum += number

    return total_sum
result = sum_even_numbers(8)
print(result)

#Q3:Function
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
print(is_prime(2))
print(is_prime(4))
print(is_prime(17))
print(is_prime(18))

#Q4:Recursion
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(2))
print(factorial(0))

#Q5:Lambda Function
multiply = lambda x, multiplier: x * multiplier
double = lambda x: multiply(x, 2)
print(double(2))
print(double(3))